name: deploy website
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: mkdir -p restricted/
      - run: echo hello > restricted/config.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: config
          path: 'restricted'

  # Single deploy job no building
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/download-artifact@main
      with:
        name: config
        path: restricted
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: restricted
    - id: deployment
      uses: actions/deploy-pages@main