name: deploy website
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: touch /config.txt
      - run: echo "can you see me??" >> /config.txt 